language: cpp

os:
- linux
- osx
- windows

dist: trusty

addons:
  apt:
    packages:
    - libudev-dev

env:
  global:
    # Supported Node versions: https://nodejs.org/en/about/releases/
  - PREBUILD_TARGETS="6.0.0 8.0.0 10.0.0 12.0.0 13.0.0"
    # Supported Electron versions: https://electronjs.org/docs/tutorial/electron-timelines
  - PREBUILD_ELECTRON_TARGETS="4.0.4 5.0.0 6.0.0 7.0.0 8.0.0"
  matrix:
  - ARCH="x64"
  - ARCH="ia32"

matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"

before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- $CXX --version
- node --version
- npm --version

install:
- npm install

script:
- |
  for target in $PREBUILD_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH
  done

  for target in $PREBUILD_ELECTRON_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH -r electron
  done
deploy:
  provider: releases
  api_key:
    # tm-rampart personal access token
    secure: "ivZseBMz+0bsYcCFAXJ82mJIhmsRj4UN32bcggg+8ZYl8xzgC2P/kMGhPe8+4fDxo+lyxf4aJDKWozE0perMQKjjAOdri8MH2ufqGFRfkF0A3gJnOBcWMA6AP3ef0TE/HNF+NMluBCV+/VFPdsvZN08rnPauWzSBGy9SkeIJhY8="
  file_glob: true
  file: prebuilds/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
