language: cpp

os:
- linux
- osx
- windows

dist: trusty

addons:
  apt:
    packages:
    - libudev-dev

env:
  global:
  - PREBUILD_TARGETS="6.0.0 8.0.0 10.0.0 11.0.0"
  - PREBUILD_ELECTRON_TARGETS="3.0.0 4.0.0 4.0.4"
  matrix:
  - ARCH="x64"
  - ARCH="ia32"

matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"

before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- $CXX --version
- node --version
- npm --version

install:
- npm install

script:
- |
  for target in $PREBUILD_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH
  done

  for target in $PREBUILD_ELECTRON_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH -r electron
  done
deploy:
  provider: releases
  api_key:
    secure: Fw/y2EJoO4oSMgBrYgsz9TV6W4LlQDs1laqEmqnJIQrEr45KnXZ7slxCe50bDWyagxjdW1h3mUL7yAeT2xjJ2d5sThmCeW8QSuKxbe/AZfm/s+sRUA8saEuVpjdaQ6ocmhTBR8eQ5n8sZocQtpKoq4sm+mvoOVKphirShnZskopsESgObJ0MGIiH1gvQ9ExiD2fQYq9545sOQNRkXLxhXwnXgwneI5oIjokaNRzkLhyZfzBoTaB8Bi3OxuobB0fd+2rDr9XIjLMUwE5WsLV8j1I5HR9jvHQKXcSRg3JE7l8dqIBkVYY4TJJ3o5rRSOT8ycl7JM2lqjbR/oqIWyfDQBRcBQW7E854KVeGwMIIVpQ2L9JjHZXa8/lbYD8nYiRBC3NRtuoMs/ZWF6F5u4u2GQg01Az3yszh0hXOEdm8NVBmXAGtkm8sLDzGutRN+gGvUPXzQ/K2Cdlrx1hGlo4mwbOLgnkUqdF5igpxm+ZU0fXkG3k6WeuIfr0MXVk9LtTGJgJUIKIQ6L9ltFWkONgEkEMJJdEicaNO36kN/ddwjSXm7nudfkF4XTNoZtRm7GmIEPM0lYFFOGsl0kuMruz6/D2+Ju+t46nBcRFgAxxZLD9RkD7bwZgzkLmfMisfkIiUF60E/9e7TpfSDKUerSpJEAUzCbSwTmc6FLwaJGvoNT8=
  file_glob: true
  file: prebuilds/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
