install:
  - ps: Install-Product node 0.10 $env:platform
  - npm install -g node-gyp
  - npm install -g node-shyp

build_script:
  - git submodule update --init
  - npm install --ignore-scripts
  - node-shyp publish --pack
  - move build\shyp\*.tgz node-usb.tgz
  - appveyor PushArtifact node-usb.tgz

platform:
  - x86
  - x64
