name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn install --ignore-scripts
      - run: yarn compile
      - run: yarn docs
      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name thegecko
          git config --global user.email github@thegecko.org
          TMPDIR=`mktemp -d`
          cp -R docs/* $TMPDIR
          git checkout gh-pages
          git pull
          git clean -fd
          cp -R $TMPDIR/* ./
          git add .
          git commit --allow-empty --message "Automatic Deployment"
          git push
